In [1]:
from nltk.corpus import stopwords
sentences = ['sky is nice','cloud are nice','Sky is nice and Cloud are nice']

cleaned_sentence = []

for sentence in sentences:
    word = sentence.lower()
    ## Lowering all the letters becaz we want it to treat uppercase and lower case words differently
    
    word = word.split()  # spliting our sentence into words
    
    ## removing stop words
    word = [i for i in word if i not in set(stopwords.words('english'))]
    word = " ".join(word)           # joining our words back to sentences
    cleaned_sentence.append(word)   # appending our preprocessed sentence into a new list
    
## printing our new list
print(cleaned_sentence)

['sky nice', 'cloud nice', 'sky nice cloud nice']


- after preprocess and apply Stop words

## Sentence-1

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 3) # give it a max feature as 3
Bagofwords = cv.fit_transform(cleaned_sentence).toarray()

print(Bagofwords)

[[0 1 1]
 [1 1 0]
 [1 2 1]]


In [3]:
import pandas as pd
pd.DataFrame(Bagofwords,columns=['cloud','nice','sky'])

cloud  nice  sky
0      0     1    1
1      1     1    0
2      1     2    1

In [4]:
cv.vocabulary_
# Unique words with index
# cloud is first word : first feature
# nice is second word : second feature
# sky is third word : third feature


{'sky': 2, 'nice': 1, 'cloud': 0}

In [11]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

sentences = ['Game of Throne is an amazing tv series!',
             'Game of Throne is the best tv series!','Game of Thrones is so great']

cleaned_sentence = []

for sentence in sentences:
    word = sentence.lower()
    ## Lowering all the letters becaz we want it to treat uppercase and lower case words differently
    
    word = word.split()  # spliting our sentence into words
    
    ## removing stop words
    word = [i for i in word if i not in set(stopwords.words('english'))]
    word = " ".join(word)           # joining our words back to sentences
    cleaned_sentence.append(word)   # appending our preprocessed sentence into a new list
    
## printing our new list
print(cleaned_sentence)

cv = CountVectorizer(ngram_range=(1,2))  #give it a max feature as 3
Bangofwords = cv.fit_transform(cleaned_sentence).toarray()

print(Bagofwords)

['game throne amazing tv series!', 'game throne best tv series!', 'game thrones great']
[[0 1 1]
 [1 1 0]
 [1 2 1]]


In [15]:
cv.vocabulary_
# Index mapping

{'sky': 4,
 'nice': 2,
 'sky nice': 5,
 'cloud': 0,
 'cloud nice': 1,
 'nice cloud': 3}

In [16]:
# All together 
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

sentences = ['sky is nice','cloud are nice','Sky is nice and Cloud are nice']

cleaned_sentence = []

for sentence in sentences:
    word = sentence.lower()
    ## Lowering all the letters becaz we want it to treat uppercase and lower case words differently
    
    word = word.split()  # spliting our sentence into words
    
    ## removing stop words
    word = [i for i in word if i not in set(stopwords.words('english'))]
    word = " ".join(word)           # joining our words back to sentences
    cleaned_sentence.append(word)   # appending our preprocessed sentence into a new list
    
## printing our new list
print(cleaned_sentence)

cv = CountVectorizer(ngram_range=(1,2))  #give it a max feature as 3
Bangofwords = cv.fit_transform(cleaned_sentence).toarray()

print(Bagofwords)

['sky nice', 'cloud nice', 'sky nice cloud nice']
[[0 1 1]
 [1 1 0]
 [1 2 1]]


In [18]:
cv.vocabulary_

# Vector formation happens based on vocabulary

{'sky': 4,
 'nice': 2,
 'sky nice': 5,
 'cloud': 0,
 'cloud nice': 1,
 'nice cloud': 3}

## TfidfVectorizer

In [19]:
Document1= "going rain today."
Document2= "Today going outside."
Document3= "going warch season premiere"
Doc = [Document1 ,Document2 ,Document3]
print(Doc)

['going rain today.', 'Today going outside.', 'going warch season premiere']


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(Doc)

In [26]:
vectorizer.vocabulary_

{'going': 0,
 'rain': 3,
 'today': 5,
 'outside': 1,
 'warch': 6,
 'season': 4,
 'premiere': 2}

In [25]:
analyze = vectorizer.build_analyzer()
print("Document 1",analyze(Document1)) # Individual tf-idf
print("Document 2",analyze(Document2))
print("Document 3",analyze(Document3))
print("Document transform",x.toarray())  # all together

Document 1 ['going', 'rain', 'today']
Document 2 ['today', 'going', 'outside']
Document 3 ['going', 'warch', 'season', 'premiere']
Document transform [[0.42544054 0.         0.         0.72033345 0.         0.54783215
  0.        ]
 [0.42544054 0.72033345 0.         0.         0.         0.54783215
  0.        ]
 [0.32274454 0.         0.54645401 0.         0.54645401 0.
  0.54645401]]


In [29]:
vectorizer.get_feature_names_out() # sorted order of vocab

array(['going', 'outside', 'premiere', 'rain', 'season', 'today', 'warch'],
      dtype=object)

In [45]:
# With out Normalization
Document1= "good movie."
Document2= "good snacks."
Document3= "movie snacks good"
Doc = [Document1 ,Document2 ,Document3]
print(Doc)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(norm=None)
x = vectorizer.fit_transform(Doc)

analyze = vectorizer.build_analyzer()
print("Document 1",analyze(Document1)) # Individual tf-idf
print("Document 2",analyze(Document2))
print("Document 3",analyze(Document3))
print("Document transform",x.toarray())  # all together

vectorizer.get_feature_names_out()

['good movie.', 'good snacks.', 'movie snacks good']
Document 1 ['good', 'movie']
Document 2 ['good', 'snacks']
Document 3 ['movie', 'snacks', 'good']
Document transform [[1.         1.28768207 0.        ]
 [1.         0.         1.28768207]
 [1.         1.28768207 1.28768207]]


array(['good', 'movie', 'snacks'], dtype=object)

In [46]:
# (count_of_term_t_in_d) * ((log (NUMBER_OF_DOCUMENTS + 1) / (Number_of_documents_where_t_appears +1)) +1)

In [47]:
import numpy as np
1 * (np.log((3 + 1)/(3+1))+1)

1.0

In [51]:
# movie
1 * (np.log((3 + 1)/(2+1))+1)

1.2876820724517808

In [52]:
tfidf_vector = [1, 1.28768207, 0]

tfidf_vector = tfidf_vector / np.linalg.norm(tfidf_vector)

print(tfidf_vector)

[0.61335554 0.78980693 0.        ]


In [53]:
# With Normalization
# With out Normalization
Document1= "good movie."
Document2= "good snacks."
Document3= "movie snacks good"
Doc = [Document1 ,Document2 ,Document3]
print(Doc)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(Doc)

analyze = vectorizer.build_analyzer()
print("Document 1",analyze(Document1)) # Individual tf-idf
print("Document 2",analyze(Document2))
print("Document 3",analyze(Document3))
print("Document transform",x.toarray())  # all together

vectorizer.get_feature_names_out()


['good movie.', 'good snacks.', 'movie snacks good']
Document 1 ['good', 'movie']
Document 2 ['good', 'snacks']
Document 3 ['movie', 'snacks', 'good']
Document transform [[0.61335554 0.78980693 0.        ]
 [0.61335554 0.         0.78980693]
 [0.48133417 0.61980538 0.61980538]]


array(['good', 'movie', 'snacks'], dtype=object)

In [54]:
tfidf_vector = [1, 1.28768207, 0]

tfidf_vector = tfidf_vector / np.linalg.norm(tfidf_vector)

print(tfidf_vector)

[0.61335554 0.78980693 0.        ]
