In [2]:
#!pip install opencv-python

## Haar cascade

- It is an object detection method

In [3]:
import cv2
import numpy as np
import warnings 
warnings.simplefilter('ignore')

## Load and read the image

In [4]:
# load on the image using 'imread' specifying the path to image

img=cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg',1)

## Lets take a closer look at how images are stored

In [5]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


## Shape give the dimension of the image array

In [6]:
img.shape

# the 3d dimensions are 1358 pixel in height * 1500 pixel wide
# 3 means that there are 3 RGB that makeup this image

(1358, 1500, 3)

## Display the image

In [7]:
# to display our image variable , we use imshow

cv2.imshow('pm', img)


# waitKey allow us to input information when a image window is open
cv2.waitKey()

# cv2.waitKey(2000) (time in milisecond)

# this close all open window
# failure to place this will cause your program to hang
cv2.destroyAllWindows()

In [8]:
img= cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg')
cv2.imshow('pm', img)
cv2.waitKey()
cv2.destroyAllWindows()

## Save the image

In [9]:
cv2.imwrite('pm_modi.jpg', img)

True

## Resize the image

In [10]:
img= cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg')

resize = cv2.resize(img,(500,500))

grey = cv2.cvtColor(resize, cv2.COLOR_BGR2GRAY)

cv2.imshow('modi image', grey)

cv2.waitKey()

cv2.destroyAllWindows()

In [11]:
img.shape[0]*0.5

679.0

In [12]:
img.shape[1]*0.5

750.0

### face Detection Using HAAR Cascade Classifiers

In [13]:
 # we point Open cv cascade classifier function to where our classifier 
face_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_frontalface_default.xml')

# load our image and convert it to grayscale

img= cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

In [14]:
print(faces)

[[205  79 217 217]]


In [15]:
face_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_frontalface_default.xml')

# load our image and convert it to grayscale

img= cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')
# we iterate through our faces array and draw rectangle
# over each face in faces

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,100),1)
    
cv2.imshow('face detection', img)
cv2.waitKey()
cv2.destroyAllWindow()
    

AttributeError: module 'cv2' has no attribute 'destroyAllWindow'

## Face and eye detection

In [16]:
face_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_eye.xml')


img= cv2.imread('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\Modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  
faces = face_classifier.detectMultiScale(grey, 1.03,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,100),2)
    roi_grey = grey[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_grey)
    
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)

    
cv2.imshow('face ', img)
cv2.waitKey()
cv2.destroyAllWindow()


AttributeError: module 'cv2' has no attribute 'destroyAllWindow'

## Capture a video

In [1]:
# doing some face recognigation with the webcam

import cv2
vedio =  cv2.VideoCapture(0) # 0--webcam

while True:
    check,frame = vedio.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('vedio', frame)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()

NameError: name 'video' is not defined

 ## face & eye detection cascade classifiers

In [ ]:

import cv2
face_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_eye.xml')

def detect( grey, frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        roi_grey = grey[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_classifier.detectMultiScale(roi_grey, 1.1,3)
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)
    return frame

# doing some face recognition with the webcam

vedio = cv2.VideoCapture(0)

while True:
    check,frame = vedio.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('vedio', gray)
    canvas = detect(grey,frame)
    
    cv2.imshow('vedio', canvas)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()        

 ## pedistrian detection

In [ ]:
import cv2
# create our body classifier
body_classifier = cv2.CascadeClassifier('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\haarcascade_fullbody.xml')

# initiate video capture for video file

cap = cv2.VideoCapture('C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\walking.avi')

# loop once video is successfully loaded

while cap.isOpened():
    
    # read first frame
    check,frame = cap.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY) 
    # pass frame to our body classifier
    
    bodies = body_classifier.detectMultiScale(grey,1.2,3)
    
    # extract bounding boxes for any bodies
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        cv2.imshow('pedestrian', frame)
    
    
    if cv2.waitKey(1)==ord('q'):
        break
        
        
cap.release()
cv2.destroyAllWindows() 
    