### Step-1

#### Read the packages

In [7]:
# Step-1: Import the packages
# Step-2: Read the data
# Step-3: EDA part
# Step-4: Divide data input and output
# Step-5: input into train test ,outpit into train test
# Step-6: Model fit
# Step-7: Prediction on x_test
# Step-8: Evaluate the model by using y_predictions with y_test
# Step-9: save the model
# Step-10: loaded the model and pass test cases

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")

In [10]:
# Step-2:
# input data
X=df.drop('quality',axis=1)
# output
y=df['quality']


# Step-3:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test=train_test_split(X,
                                                y,
                                                test_size=0.2,
                                                random_state=1234)

# Step-4:
print(df.shape)  

print(X_train.shape)  
print(X_test.shape)   
print(y_train.shape)  
print(y_test.shape)

(1599, 12)
(1279, 11)
(320, 11)
(1279,)
(320,)


In [11]:
from statsmodels.api import OLS

In [12]:
results=OLS(y_train,X_train).fit()

In [13]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                quality   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              8645.
Date:                Sun, 30 Mar 2025   Prob (F-statistic):                        0.00
Time:                        16:10:08   Log-Likelihood:                         -1270.3
No. Observations:                1279   AIC:                                      2563.
Df Residuals:                    1268   BIC:                                      2619.
Df Model:                          11                                                  
Covariance Type:            nonrobust                                                  
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
fixed acidity           -0.0084      0.019     -0.450      0.653      -0.045       0.028
volatile acidity        -1.1035      0.134     -8.256      0.000      -1.366      -0.841
citric acid             -0.1079      0.165     -0.654      0.513      -0.432       0.216
residual sugar           0.0063      0.013      0.469      0.639      -0.020       0.033
chlorides               -1.7285      0.460     -3.760      0.000      -2.630      -0.827
free sulfur dioxide      0.0050      0.002      2.063      0.039       0.000       0.010
total sulfur dioxide    -0.0037      0.001     -4.429      0.000      -0.005      -0.002
density                  4.7359      0.706      6.710      0.000       3.351       6.121
pH                      -0.5526      0.180     -3.068      0.002      -0.906      -0.199
sulphates                0.8218      0.123      6.696      0.000       0.581       1.063
alcohol                  0.2988      0.020     15.289      0.000       0.260       0.337
==============================================================================
Omnibus:                       15.143   Durbin-Watson:                   2.094
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.632
Skew:                          -0.152   Prob(JB):                     5.46e-05
Kurtosis:                       3.526   Cond. No.                     2.43e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.43e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

**Hypothesis testing in linear  regression**

H0: There is no relation between dependent and independent variable

H1: There is a relation
    
p<alpha , 
p<0.05 

    - Null hypothesis is rejected
    
    - Relation is there
    
    - Corresponding variable can use for model development
    
From above summary 

- Fixed acidity p-value: 0.6
    
- Citric acid p-value: 0.5 
    
- Residual sugar p-value: 0.6 
    
**The above  3 columns need to exclude from the model development**  

In [ ]:
AIC - Akaike information criterion

    - what is the formula?
    
    - AIC = 2k - 2ln(L^)
    
- AIC	=	Akaike information criterion
- k 	=	number of estimated parameters in the model
- {L^}  =	maximum value of the likelihood function for the model

    - what could be batter incraese or decrease?
    
    -  a lower AIC score generally indicates a better-fitting model.
    

BIC - 

ISLP:

In [ ]:
col1   col2    col3

R2(col1,col2)
R2(col1,col3)

col1 as output col2 as input

VIF = 1/(1-R^2)

In [15]:
results.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                        Results: Ordinary least squares
===============================================================================
Model:                  OLS              Adj. R-squared (uncentered): 0.987    
Dependent Variable:     quality          AIC:                         2562.6451
Date:                   2025-03-30 16:11 BIC:                         2619.3372
No. Observations:       1279             Log-Likelihood:              -1270.3  
Df Model:               11               F-statistic:                 8645.    
Df Residuals:           1268             Prob (F-statistic):          0.00     
R-squared (uncentered): 0.987            Scale:                       0.43050  
---------------------------------------------------------------------------------
                         Coef.    Std.Err.      t      P>|t|     [0.025    0.975]
---------------------------------------------------------------------------------
fixed acidity           -0.0084     0.0186   -0.4498   0.6530   -0.0449    0.0281
volatile acidity        -1.1035     0.1337   -8.2562   0.0000   -1.3657   -0.8413
citric acid             -0.1079     0.1650   -0.6537   0.5134   -0.4316    0.2159
residual sugar           0.0063     0.0134    0.4686   0.6394   -0.0200    0.0326
chlorides               -1.7285     0.4597   -3.7603   0.0002   -2.6303   -0.8267
free sulfur dioxide      0.0050     0.0024    2.0631   0.0393    0.0002    0.0098
total sulfur dioxide    -0.0037     0.0008   -4.4287   0.0000   -0.0053   -0.0021
density                  4.7359     0.7058    6.7096   0.0000    3.3511    6.1206
pH                      -0.5526     0.1801   -3.0684   0.0022   -0.9060   -0.1993
sulphates                0.8218     0.1227    6.6956   0.0000    0.5810    1.0626
alcohol                  0.2988     0.0195   15.2891   0.0000    0.2605    0.3371
-------------------------------------------------------------------------------
Omnibus:                  15.143            Durbin-Watson:               2.094 
Prob(Omnibus):            0.001             Jarque-Bera (JB):            19.632
Skew:                     -0.152            Prob(JB):                    0.000 
Kurtosis:                 3.526             Condition No.:               2429  
===============================================================================
* The condition number is large (2e+03). This might indicate             strong
multicollinearity or other numerical problems.
"""

In [16]:
results.params

fixed acidity          -0.008370
volatile acidity       -1.103458
citric acid            -0.107870
residual sugar          0.006285
chlorides              -1.728471
free sulfur dioxide     0.005032
total sulfur dioxide   -0.003695
density                 4.735879
pH                     -0.552635
sulphates               0.821807
alcohol                 0.298795
dtype: float64

In [17]:
# I shared one note boook
# Different between stats model vs linear model
# just run that understand

### Feature-Selection

**Rerival the important feature, selection an important features is very important stepbefore going to**

- Dropping the constant feature
- Information gain
- p-value
- Forward selection and backward selection
- correlection with target column

### Method -1: Variance threshold method

#### Droping constant feature

- If the feature or variables having zero variance
- The feature value through out the data is the same
- You can decide manually what is your desired variance in order to keep the feature 



In [18]:
import pandas as pd
dict1={'A':[100,200,300,400],
       'B':[1,2,3,4],
       'C':[10,20,30,40],
       'D':[10,10,10,10]}

df=pd.DataFrame(dict1)
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [19]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
vt.fit(df)

VarianceThreshold(threshold=0)

In [20]:
dir(vt)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_transform',
 '_validate_data',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_params',
 'get_support',
 'inverse_transform',
 'n_features_in_',
 'set_params',
 'threshold',
 'transform',
 'variances_']

In [21]:
df

# The column D is not changing
# The column D has same value
# Same value means the variance = 0
# I keep threshold=0
# D should remove

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [22]:
vt.get_support()

# True: the variance not equal to zero
# False: the variance is equal to zero

array([ True,  True,  True, False])

In [23]:
# I need the columns those have support=true
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

**if the values are consant and if one value is Zerowe will remove that row or column**

- you want to drop the column : if that column is unless

- The data is not changing  much : variance is zero  


In [24]:
vt.get_params()

{'threshold': 0}

In [25]:
vt.get_support()

array([ True,  True,  True, False])

In [26]:
cols=df.columns[vt.get_support()]
cols
# D is remove

Index(['A', 'B', 'C'], dtype='object')

In [27]:
support=vt.get_support()
for i in range (len(support)):
    if support[i]==True:
        print(df.columns[i])

A
B
C


In [ ]:
# Task: implement the same task on wine data
# change the threshold
# keep 0
# keep 0.5
df=#data
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
vt.fit(df)

cols=df.columns[vt.get_support()]
cols

In [39]:
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [40]:
df[cols]

A  B   C
0  100  1  10
1  200  2  20
2  300  3  30
3  400  4  40

In [41]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
vt.fit(df)

cols=df.columns[vt.get_support()]
df[cols]

# Don't do on target variable
# Whileprvoiding the data remove the target variable 

A  B   C
0  100  1  10
1  200  2  20
2  300  3  30
3  400  4  40

In [42]:
import pandas as pd
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [43]:
# Apply only Input columns
# Drop the target column: quality
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [44]:
# Separate input and output column
X=data.drop('quality',axis=1)
# inplace=True data will with out quality
# don't apply inplace True
X.columns
print(X.shape)
y=data['quality']

(1599, 11)


In [45]:
# Here in two examples I have taken numerical data
# Will convert categorical data to numerical data developing the ML algorithm
# thas why here im using only numerical data

In [46]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1)
vt.fit(X)

cols=X.columns[vt.get_support()]
X[cols]

fixed acidity  residual sugar  free sulfur dioxide  \
0               7.4             1.9                 11.0   
1               7.8             2.6                 25.0   
2               7.8             2.3                 15.0   
3              11.2             1.9                 17.0   
4               7.4             1.9                 11.0   
...             ...             ...                  ...   
1594            6.2             2.0                 32.0   
1595            5.9             2.2                 39.0   
1596            6.3             2.3                 29.0   
1597            5.9             2.0                 32.0   
1598            6.0             3.6                 18.0   

      total sulfur dioxide  alcohol  
0                     34.0      9.4  
1                     67.0      9.8  
2                     54.0      9.8  
3                     60.0      9.8  
4                     34.0      9.4  
...                    ...      ...  
1594                  44.0     10.5  
1595                  51.0     11.2  
1596                  40.0     11.0  
1597                  44.0     10.2  
1598                  42.0     11.0  

[1599 rows x 5 columns]

In [47]:
if complete row is NAN can we drop NAN values

# Many approaches ==== R & D
# 100 : 50 NAN

SyntaxError: invalid syntax (1806251614.py, line 1)

In [48]:
######################## ALL COMBIND ########################################
import pandas as pd
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")
data.head()

X=data.drop('quality',axis=1)
y=data['quality']

from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1)
vt.fit(X)

cols=X.columns[vt.get_support()]
X[cols]

# What is the threshold you need to keep : no answer

# pH column is not removed which means its variance is not zero

fixed acidity  residual sugar  free sulfur dioxide  \
0               7.4             1.9                 11.0   
1               7.8             2.6                 25.0   
2               7.8             2.3                 15.0   
3              11.2             1.9                 17.0   
4               7.4             1.9                 11.0   
...             ...             ...                  ...   
1594            6.2             2.0                 32.0   
1595            5.9             2.2                 39.0   
1596            6.3             2.3                 29.0   
1597            5.9             2.0                 32.0   
1598            6.0             3.6                 18.0   

      total sulfur dioxide  alcohol  
0                     34.0      9.4  
1                     67.0      9.8  
2                     54.0      9.8  
3                     60.0      9.8  
4                     34.0      9.4  
...                    ...      ...  
1594                  44.0     10.5  
1595                  51.0     11.2  
1596                  40.0     11.0  
1597                  44.0     10.2  
1598                  42.0     11.0  

[1599 rows x 5 columns]

In [49]:
X['pH'].std()

0.15438646490354266

In [50]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [51]:
import pandas as pd
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")
data.head()

X=data.drop('quality',axis=1)
y=data['quality']


In [52]:
# This is not required only for check

import numpy as np
list_var=[]
for i in X.columns:
    list_var.append(np.sqrt(X[i].std()))
    
for i in list_var:
    if i<1:
        print(i,list_var.index(i),X.columns[list_var.index(i)])
    

0.42315446843148774 1 volatile acidity
0.44136281833126567 2 citric acid
0.21694538946492997 4 chlorides
0.04344345697389373 7 density
0.39292043075353394 8 pH
0.41171225338834616 9 sulphates


In [53]:
list1=['A','B']
list1.index('A')

0

## Method-2:

### Information gain

**mutual info classify**

- It is value estimating how much relationship/how much information about target variable

- 27% information about target variable

- 0 means both variables are independent



In [54]:
# quality of the wine

# total sulfur dioxide: so2 is not having relation with quality
# 100 columns are there : you can select top 20 columns
# Which are having relation with the target variable

# This is the concept of mutual info classify

In [55]:
# relation b/w input vs output (required) ======= mutual info classify

# relation among the input columns (not required) ====== multicolineraity

In [56]:
import pandas as pd

# Read the data
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")

# Separate input and target feature
X=data.drop('quality',axis=1)  # X is dataframe
y=data['quality']  # y is series type


In [57]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [58]:
# data[['fixed acidity','volatile acidity']]

In [59]:
#YY=data['quality']
#YY

In [60]:
from sklearn.feature_selection import mutual_info_classif
MI=mutual_info_classif(X,y)
MI

array([0.05141408, 0.1332759 , 0.05829312, 0.0279932 , 0.03755674,
       0.03172115, 0.0672938 , 0.08207248, 0.01799864, 0.10628686,
       0.16882647])

In [61]:
len(MI)

11

In [62]:
val=pd.Series(MI)
val

# I want replace index with column names

0     0.051414
1     0.133276
2     0.058293
3     0.027993
4     0.037557
5     0.031721
6     0.067294
7     0.082072
8     0.017999
9     0.106287
10    0.168826
dtype: float64

In [63]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [64]:
MI    # Numpy array

# Numpy array we are convrting into series

array([0.05141408, 0.1332759 , 0.05829312, 0.0279932 , 0.03755674,
       0.03172115, 0.0672938 , 0.08207248, 0.01799864, 0.10628686,
       0.16882647])

In [65]:
# Two method almost enough
# Constan feature  ==== you need to remove
# Mutual information

val=pd.Series(MI)   # index with series
val.index=X.columns # column with series
val

fixed acidity           0.051414
volatile acidity        0.133276
citric acid             0.058293
residual sugar          0.027993
chlorides               0.037557
free sulfur dioxide     0.031721
total sulfur dioxide    0.067294
density                 0.082072
pH                      0.017999
sulphates               0.106287
alcohol                 0.168826
dtype: float64

In [66]:
val.sort_values(ascending=True)

# What is meant by pH= 0.0000 ?
# What is these all values?

# pH and target column both are independent each other

pH                      0.017999
residual sugar          0.027993
free sulfur dioxide     0.031721
chlorides               0.037557
fixed acidity           0.051414
citric acid             0.058293
total sulfur dioxide    0.067294
density                 0.082072
sulphates               0.106287
volatile acidity        0.133276
alcohol                 0.168826
dtype: float64

In [67]:
# Hand  kamber read this book

In [68]:
# In mutualinfo it will give that give that relation ship between input and output

# number of input columns are 11

# 11 values

# pd.Serices(11)

# index === column === sort === 5

# selectKbest k=5 ===== > top 5 columns

## SelectKbest

In [69]:
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [72]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
import pandas as pd

# Read the data
data=pd.read_csv("C:\\Users\\sony\\ DATA SCIENCE  NARESH IT\\winequality_red.csv")

# Separate input and target feature
X=data.drop('quality',axis=1)
y=data['quality']

# Assume that you did not done mutual info classif
top_5=SelectKBest(mutual_info_classif,k=5)
val=top_5.fit(X,y)



In [73]:
val.get_support()

array([False,  True, False, False, False, False,  True,  True, False,
        True,  True])

In [75]:
val.get_feature_names_out()  # Which is True

array(['volatile acidity', 'total sulfur dioxide', 'density', 'sulphates',
       'alcohol'], dtype=object)

In [76]:
val.get_params() # Whatever you pass inside package

{'k': 5,
 'score_func': <function sklearn.feature_selection._mutual_info.mutual_info_classif(X, y, *, discrete_features='auto', n_neighbors=3, copy=True, random_state=None)>}

In [78]:
val.scores_    # This is relationship score

array([0.0457647 , 0.12618822, 0.07411493, 0.01702507, 0.0512067 ,
       0.0419724 , 0.07489869, 0.07874618, 0.01405101, 0.09267233,
       0.18205725])